services:
  server:
    image: gitea/gitea:1
    container_name: gitea

    environment:
      GITEA__database__DB_TYPE: postgres
      GITEA__database__HOST: db:5432

    env_file:
      - stack.env

    restart: unless-stopped

    depends_on:
      - db

    networks:
      - traefik
      - gitea

    volumes:
      - data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

    expose:
      - 3000

    ports:
      - 44832:22

    labels:
      - traefik.enable=true
      - traefik.http.routers.gitea.entrypoints=https
      - traefik.http.routers.gitea.rule=Host(`${HOST}`)
      - traefik.http.routers.gitea.service=gitea
      - traefik.http.services.gitea.loadbalancer.server.port=3000

    security_opt:
      - no-new-privileges:true

  db:
    image: postgres:14
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${GITEA__database__NAME}
      - POSTGRES_USER=${GITEA__database__USER}
      - POSTGRES_PASSWORD=${GITEA__database__PASSWD}
    networks:
      - gitea
    volumes:
      - postgres:/var/lib/postgresql/data

networks:
  gitea:
  traefik:
    external: true

volumes:
  data:
    name: gitea-data
    external: true
  postgres:
    name: gitea-postgres
    external: true
